# Generated by Django 2.2.27 on 2022-03-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('nombre',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('nombre',), 'verbose_name': 'producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='existencia',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='shop.Category'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'descripcion')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
