# Generated by Django 2.2.27 on 2022-03-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220321_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoria',
        ),
    ]
